apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: my_node_application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my_node_application
  template:
    metadata:
      labels:
        app: my_node_application
    spec:
      containers:
      - name: node-app-container
        image: divyansh2301/node_app:v1
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://node-app-db-service:27017/myapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-db-deployment
  labels:
    app: my_node_application
spec:
  selector:
    matchLabels:
      app: my_node_application
  replicas: 1
  template:
    metadata:
      labels:
        app: my_node_application
    spec:
      containers:
      - name: node-app-db-container
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: node-app-db-storage
          mountPath: /data/db
      volumes:
      - name: node-app-db-storage
        persistentVolumeClaim:
          claimName: node-app-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: node-app-db-service
  labels:
    app: my_node_application
spec:
  selector:
    app: my_node_application
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    app: my_node_application
spec:
  selector:
    app: my_node_application
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000