apiVersion: v1
kind: Service
metadata:
  name: node-app-service-external-lb
spec:
  selector:
    app: my_node_application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
